version: '3.4'

services:
  basketdb:
    image: postgres

  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
    postgres_basket:
    postgres_catalog:

